# site properties and page defaults
title: Evolutionary genomics of pathogens
subtitle: Croll lab at University of Neuchatel
description: The lab of Daniel Croll wants to understand how pathogens evolve to cause disease. For this, we mainly focus on major crop pathogens to unravel mechanisms of rapid adaptation. We want to understand how host resistance mechanisms are circumvented, pesticides become ineffective and how pathogens cope with climate challenges.
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: daniel.croll@unine.ch
  orcid: 0000-0002-2072-380X
  google-scholar: 82WR4DYAAAAJ
  github: crolllab
  twitter: danielcroll
  

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
