- id: doi:10.1101/2023.03.29.534750
  type: preprint
  image: https://www.biorxiv.org/content/biorxiv/early/2023/03/29/2023.03.29.534750/F3.large.jpg?width=800&height=600&carousel=1
  tags: 
    - bioRxiv
    - TEs
    - Zymoseptoria
- id: doi:10.1101/2023.03.29.534637
  type: preprint
  image: https://www.biorxiv.org/content/biorxiv/early/2023/03/29/2023.03.29.534637/F5.large.jpg?width=800&height=600&carousel=1
  tags: 
    - bioRxiv
    - TEs
    - Zymoseptoria
- id: doi:10.1101/2022.12.23.521735
  type: preprint
  image: 
  tags: 
    - bioRxiv
- id: doi:10.1101/2022.09.28.509846
  type: preprint
  image: 
  tags: 
    - bioRxiv
- id: doi:10.1101/2022.05.16.492091
  type: preprint
  image: 
  tags: 
    - bioRxiv
- id: doi:10.1101/203455
  type: preprint
  image: 
  tags: 
    - bioRxiv
- id: doi:10.5281/zenodo.4655959
  type: dataset
  image: 
  tags: 
    - Zenodo
- id: doi:10.1111/mpp.12485
- id: doi:10.1111/mpp.12486
- id: doi:10.1371/journal.ppat.1002608
  type: review
  image: https://journals.plos.org/plospathogens/article/figure/image?size=large&id=10.1371/journal.ppat.1002608.g001
  tags: 
    - Highlight
    - Review
- id: doi:10.1002/bies.201400030
- id: doi:10.1002/bies.201600195
- id: doi:10.1007/s10658-012-0080-8
- id: doi:10.1007/s10681-021-02843-7
- id: doi:10.1007/s13225-012-0171-z
- id: doi:10.1007/s42161-021-00952-9
- id: doi:10.1016/B978-0-12-819990-9.00042-1
- id: doi:10.1016/j.csbj.2020.12.018
- id: doi:10.1016/j.cub.2010.05.031
- id: doi:10.1016/j.cub.2011.10.041
  type: paper
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0960982211012024-gr3.jpg
  tags: 
    - Highlight
    - Zymoseptoria
- id: doi:10.1016/j.fbr.2014.02.001
- id: doi:10.1016/j.fbr.2020.07.001
- id: doi:10.1016/j.fgb.2015.05.001
- id: doi:10.1016/j.fgb.2017.08.007
- id: doi:10.1016/j.fgb.2020.103398
- id: doi:10.1016/j.mib.2018.01.020
- id: doi:10.1016/j.pbi.2020.04.009
- id: doi:10.1016/j.simyco.2021.100116
- id: doi:10.1016/j.tig.2021.08.005
  type: review
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0168952521002298-gr1.jpg
  tags: 
    - Highlight
    - Review
- id: doi:10.1016/j.tig.2022.05.008
  type: review
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0168952522001160-gr1.jpg
  tags: 
    - Review
- id: doi:10.1016/j.tig.2023.01.005
  type: review
  image: https://www.cell.com/cms/attachment/10c60bb2-af4c-42cc-90cb-dda29c8cab23/b1.jpg
  tags: 
    - Conservation genomics
    - Review
- id: doi:10.1016/j.tree.2016.12.005
  type: review
  image: https://ars.els-cdn.com/content/image/1-s2.0-S0169534716302385-gr1.jpg
- id: doi:10.1016/j.tree.2021.11.008
  type: review
  image: https://ars.els-cdn.com/content/image/1-s2.0-S016953472100313X-gr1.jpg
- id: doi:10.1038/hdy.2015.111
- id: doi:10.1038/ismej.2016.196
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fismej.2016.196/MediaObjects/41396_2017_Article_BFismej2016196_Fig1_HTML.jpg?as=webp
  tags: 
    - Highlight
    - Zymoseptoria
- id: doi:10.1038/s41396-020-00859-w
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41396-020-00859-w/MediaObjects/41396_2020_859_Fig1_HTML.png?as=webp
  tags: 
    - Highlight
    - Zymoseptoria
- id: doi:10.1038/s41396-020-0729-9
- id: doi:10.1038/s41437-020-0306-z
- id: doi:10.1038/s41467-020-14803-1
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-020-14803-1/MediaObjects/41467_2020_14803_Fig1_HTML.png?as=webp
  tags: 
    - Highlight
    - Conservation genomics
- id: doi:10.1038/s41467-021-23862-x
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-021-23862-x/MediaObjects/41467_2021_23862_Fig1_HTML.png?as=webp
  buttons:
    - type: source
      text: Github
      link: https://github.com/crolllab/datasets
  tags: 
    - Highlight
    - Zymoseptoria
- id: doi:10.1038/s41467-023-36674-y
  type: paper
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-023-36674-y/MediaObjects/41467_2023_36674_Fig2_HTML.png?as=webp
  buttons:
    - type: source
      text: Github
      link: https://github.com/afeurtey/WW_PopGen  
  tags: 
    - Highlight
    - TEs
    - Zymoseptoria 
- id: doi:10.1039/9781839163005-00257
  type: paper
  image: 
  tags: 
    - Highlight
- id: doi:10.1093/gbe/evaa203
  type: paper
  image: 
  tags: 
    - Highlight
- id: doi:10.1093/gbe/evs091
  type: paper
  image: 
  tags: 
    - Highlight
- id: doi:10.1093/gbe/evy087
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/gbe/10/5/10.1093_gbe_evy087/1/m_evy087f1.jpeg?Expires=1685519877&Signature=Tau2a68L2f4vxr49~Ex2a0LTii~8p874vN6SYvmIV5wDE2lZmdF52oR4ASNRFLOjWcltIBRBKDZZ5f6GtDAgn~5UHCDd61OJsNjS05Wmfuc3UoM4piFCr3jXCIZhFWGH6kGpcALRUnwO1H2Rih04Bi8p~iTOQfJ2nzVi1~m0Vl-Qi-NgSaEi~tYZf714qSkruCy3P7peLpW25jD7Y5BGxSU2Ep1SS0E0B3qDa298RQpetSjzMl~TXnApYr9gMK~fWncNbPIdKp39R5qCzWA7EMYIuVnzMSkA8WiLMz5Br1Tjx9xKp5FJ0C3diZegdAv2HucNZ5fqBdd4Q~Fp3wj7rA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Rhynchosporium
- id: doi:10.1093/gbe/evy100
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/gbe/10/6/10.1093_gbe_evy100/1/m_evy100f2.jpeg?Expires=1685993564&Signature=oD~ZJNO~jSpUtDt2y0M4d4KsY8ZsFildPMCUm2-maZ92BuBsFEsY911-e~a-3eTG8LgP0XU7zec7GqwsyurzrO8bsgcfbHw-lILLuvXF22bUckSw5svJeitOYMjjjr5DxoT0a1jjvhN6If50nCKLRVXKYPQkOAFkrDhc7KX0mTOzR4v19qsvF3UW7VD--VIAfbGRJX8lQY-KO~z-egOmLXRFIqJ5AXsiXy81IrCigFVQInpoR5P2LlWBUyBj3P6H55XoVa1s-m6jGzTzh9O-yCH6WY5Gb9jjfg1s1Df6fqdxF4Vk9ujXZih23V28W0kIfk14BdsFqzJ69vsMdpyStg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Zymoseptoria
- id: doi:10.1093/gbe/evz225
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/gbe/11/11/10.1093_gbe_evz225/2/m_evz225f2.jpeg?Expires=1685700151&Signature=Eh40PjZIMrMJGdoV8rxSBXOpCebe3dya31r2SIfw6Oew-f5pEzKSBLjhhv92ZkFNbxP8LKgrUCQ43mJ3fn2FCrXTzYTkwLEjPFUpEPT3cI0717UB34G0gXA-gTTwKaIKyTUbLBcuiIhoU8hfihdYeYQE8cO-d9dU8oCSHNaoH3ftDXnAMYutcCVgYMvdZuZODjRv3QyYcRRG0lVK6RdHEOlo1qUokakED~C4xQsy~ifqiI5WjkuR-bDm9llOfGTrxoo9aDVSydTlsv-K22W5eq9LWfWYC2ApZ-jk503RG6L6xHepcE0sK0f1S2-pbr~iG9Z4GYVnpqHi8bTgYly~Xw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Fusarium
- id: doi:10.1093/gigascience/giac090
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/gigascience/11/10.1093_gigascience_giac090/2/giac090fig1.jpeg?Expires=1685759088&Signature=sYBxGTiJBF-jnKbuAazVi-ACMznC6WB7cI7UKkjTv1xLESr1jT6741lLEA3B80s~KJO~8dIh2N5~4SqxYHTIP-icsLAPy~fKmLRcZpl2gnK-zEB3~ePNNkhfXA9bUrYeCFXbqhcaSYRZ8qcmt6NSelJlFPOsB-QuMTxidBKYnGoESe-5u1FNkhWCxQygfNfvPyQVjlP3XAesgaBQ~IJ~EvWwhDh6B4qI0mIMHcPlvy3SlO1Z-3xMEXARCQmyW6gatb-o03tpd2nMGJm-898M0ZbgsdyfeIuSX7GTcP-097VGX7TydzIVDphJC8y9Up9IdCGF8pZsfYp78TTz0JlZ0w__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Conservation genomics
- id: doi:10.1093/molbev/msab323
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/mbe/39/1/10.1093_molbev_msab323/1/msab323f1.jpeg?Expires=1685971830&Signature=QaedLnp6tz9rvm7FJuIEAGieBMYINe0fz2Hor~-fzByGYNUzZOVGlIJNjyi-sI04FskD6jj3768W-HUPcbFVhnHuziLXttKztFVZYUV4N9L1WyMqIxkKzl0T3CAcuLZnS349vh9ks16b2RK1otWiPD~W-VbFzzaaAnc3qRHkOgyzojVGePzFx-MbrdA2TmbYfV5LSsD-KTMkhqD1nekagmoB7iAqbgoesR2a-9SxCAdq1nqtUmiSrlFsucDFKGtYqUYEZV1vDEGxob3wsFusOLVHdee0IPUXj1-039V0QsOVTyXKBmwBJkpHUFp87viBn6l3gOfSvlBQwfeHREjj7w__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Highlight
- id: doi:10.1093/molbev/mst041
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/mbe/30/6/10.1093_molbev_mst041/2/mst041f5p.jpeg?Expires=1685971914&Signature=plSbT3RfXo~-DIw5pclHN0yFs7YNwlx6hYh-Zrn8ZPe6XAFan~SiPNYx-uzL9LieTYz-q15DK~hC-kQEmtw617iEgn1k3x2xbgwSWzNqy02rAftPR0hapJ6Lc52ttxfR8Z0xh4UGQ8F4b9GqGpk~dk~zsDu7BMXbfmX29HZ7uER77z07CuNkB9aEl~oAKaKKk826GAAZrGh4CiLsWevl7dWYvBoPC6~oK~ONARw9eeAC4k0~9~Nkl-IO9GMVsjWcEg-EuIHCSvTWbqkNS8y4rdyWM2hEj5Uwn9sN0PSZT5qVIxf32SFoPXO-LvgHak3txz1f5mcL4H355ivl6HpWvQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Zymoseptoria
- id: doi:10.1093/molbev/msu123
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/mbe/31/7/10.1093_molbev_msu123/1/msu123f1p.jpeg?Expires=1685972088&Signature=cRPYUoqcCg-oACBpL~ZpxddDeLh2S2Sfdzs~zJuo6MxAroHkQVQ-68PxeDuRmp9eHgwOxKzyk7hbZMEStOdRMNvc7uHlX1b0PVEOdBTbmTCrOMv-Nwpug0zIwpV3ulD6pMLCxIOmTdXi6WYDvANBw2qQaDMToq9hLWQZDHD7I1hj~zrIFiP1lWHt09jzrEohnjMlLr5uzhDPzaC-QkIl4ePLDyqLy1jcZGhd52a6Bj-ieu6ENMfRMYp00XoAbYS9csHg4UXWl~JAzEoFY20oTxXfV0uaayceKEfUN-2eNHZVGgIL4f0atPkXsWTzzkrlG4dqTN0CpGJ47Z4q4736Ug__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Zymoseptoria
- id: doi:10.1093/molbev/msx208
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/mbe/34/11/10.1093_molbev_msx208/4/msx208f1.jpeg?Expires=1685971982&Signature=Ovu1w2Mik5kHfT6Vx~iLcIOBU3iTQvzRZgb1Wh2kw-FQhRxoVjW7r4JYCdLV1pjMijlARDOi3-KH7jK6pgr0K8A-aGzxBcfVRMhs2a-pmkF9FwQS0VxreIiw7FURamnogf-HBaOVWvl76vLIsbonB9v6~YDzB8YE8OLpCtHTnkfG60M4qra0r1-r2fB8HBS06ixvEBp6p-JKhgx~otrYe8xwltY367~74H8TAJgsFppBtR116Nsnr7vwbsnSIVa5RPZCRvh95tNevlAKZGkUKFENNQoyJAeebJUJIIVsLOfuRIQ~NsofDzc-wqF5tepVyuvgevN00hEFovHE8u-p7Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Highlight
    - Zymoseptoria
- id: doi:10.1093/molbev/msz216
  type: paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/mbe/37/1/10.1093_molbev_msz216/1/msz216f2.jpeg?Expires=1685972051&Signature=ZfAq3gcliRWk6hEkeMz-x9uK6~GB1CrIKSUcFaIeOC2qE1qWLN2f2~YKi9Dlh1pavPEmf4hEA0CnTA3vQWKCi0J81XUab0OG02jc22Bhwd~Vv7OqQhmoOrlmSNt64VTo81vJVQ~7wTqNFkej7jPCwwYEJNTiLesEwS9xyVpHXWJzogbZ8EoVhC7wD5pTtTrACXntq1W5JprljovAVQr5Dpix0cGpbHXrzcou2fsT3j9MdBk3j6vaP43Urc7H4LBJq8annw8IR2CulvZYzz3HzGeUctEi70HaZ3I4Z5RSuCBQX2yMDEm7eswNZMS0AJKW9zPPi56Mv4U5XFUWA9R~3w__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags: 
    - Highlight
    - TEs
    - Zymoseptoria
- id: doi:10.1094/MPMI-07-16-0146-R
- id: doi:10.1094/PHYTO-06-18-0199-LE
- id: doi:10.1099/mgen.0.000540
- id: doi:10.1099/mgen.0.000678
- id: doi:10.1101/2022.07.18.500446
  type: preprint
  image: 
  tags: 
    - bioRxiv
- id: doi:10.1101/2022.10.31.514577
  type: preprint
  image: 
  tags: 
    - bioRxiv
- id: doi:10.1111/1462-2920.14583
- id: doi:10.1111/1462-2920.15752
- id: doi:10.1111/1755-0998.13452
- id: doi:10.1111/1755-0998.13478
- id: doi:10.1111/aje.12888
- id: doi:10.1111/eva.12490
- id: doi:10.1111/eva.13117
- id: doi:10.1111/j.1420-9101.2011.02239.x
- id: doi:10.1111/j.1461-0248.2005.00853.x
- id: doi:10.1111/j.1469-8137.2008.02381.x
- id: doi:10.1111/j.1469-8137.2008.02602.x
- id: doi:10.1111/j.1469-8137.2008.02726.x
- id: doi:10.1111/j.1469-8137.2011.03948.x
- id: doi:10.1111/j.1469-8137.2011.03948.x
- id: doi:10.1111/mec.13751
- id: doi:10.1111/mec.13870
- id: doi:10.1111/mec.13916
- id: doi:10.1111/mec.14585
- id: doi:10.1111/mec.14711
- id: doi:10.1111/mec.15737
- id: doi:10.1111/mec.16386
- id: doi:10.1111/mec.16435
- id: doi:10.1111/mmi.13894
- id: doi:10.1111/mpp.12333
- id: doi:10.1111/mpp.12391
- id: doi:10.1111/mpp.12515
- id: doi:10.1111/mpp.12592
- id: doi:10.1111/mpp.12747
- id: doi:10.1111/myc.12296
- id: doi:10.1111/nph.14203
- id: doi:10.1111/nph.14434
- id: doi:10.1111/nph.15180
- id: doi:10.1111/pce.14184
- id: doi:10.1111/ppa.12111
  type: paper
  image: https://bsppjournals.onlinelibrary.wiley.com/cms/asset/0f52dff7-5a47-4407-8afd-a6a162188fa4/ppa12111-fig-0001-m.png
  tags:
    - Rhynchosporium
- id: doi:10.1126/science.abo2401
  type: paper
  image: 
- id: doi:10.1128/AEM.01574-06
- id: doi:10.1128/AEM.01908-18
- id: doi:10.1128/AEM.01974-08
- id: doi:10.1128/mBio.01231-16
  type: paper
  image: https://journals.asm.org/cms/10.1128/mBio.01231-16/asset/85a9499f-f153-4073-ae3b-3cecf04df541/assets/graphic/mbo0051630280001.jpeg
  tags:
    - Zymoseptoria
- id: doi:10.1128/mBio.01494-14
  type: paper
  image: https://journals.asm.org/cms/10.1128/mBio.01494-14/asset/e3558f35-2395-4873-925e-b099074289cd/assets/graphic/mbo0041419210008.jpeg
  tags:
    - Human pathogens
- id: doi:10.1128/mBio.01862-15
  type: paper
  image: https://journals.asm.org/cms/10.1128/mBio.01862-15/asset/ee1ba721-7c6d-47ce-9b76-30c8e09ef804/assets/graphic/mbo0061525880003.jpeg
  tags:
    - Human pathogens
- id: doi:10.1128/mBio.02377-18
  type: paper
  image: https://journals.asm.org/cms/10.1128/mBio.02377-18/asset/49803a3c-953a-4665-b3d7-45fdba8a42d3/assets/graphic/mbo0061842040002.jpeg
  tags:
    - Human pathogens
- id: doi:10.1128/mSphere.00737-20
- id: doi:10.1128/spectrum.00506-22
  type: paper
  image: https://journals.asm.org/cms/10.1128/spectrum.00506-22/asset/2f734217-262a-450c-a686-e5c671ead678/assets/images/medium/spectrum.00506-22-f004.gif
  tags:
    - Human pathogens
- id: doi:10.1128/spectrum.02513-22
  type: paper
  image: https://journals.asm.org/cms/10.1128/spectrum.02513-22/asset/7c8dbf9a-c852-4c77-968a-914b40ea236a/assets/images/medium/spectrum.02513-22-f001.gif
  tags:
    - Zymoseptoria
- id: doi:10.1128/spectrum.04443-22
  type: paper
  image: https://journals.asm.org/cms/10.1128/spectrum.02513-22/asset/7c8dbf9a-c852-4c77-968a-914b40ea236a/assets/images/medium/spectrum.02513-22-f001.gif
  tags:
    - Microbiome
- id: doi:10.1146/annurev-genet-102108-134239
- id: doi:10.1146/annurev-phyto-080417-050036
  type: review
  image: 
  tags:
    - Review
    - Wheat blast
- id: doi:10.1146/annurev-phyto-080516-035303
  type: review
  image: https://www.annualreviews.org/na101/home/literatum/publisher/ar/journals/content/phyto/2018/phyto.2018.56.issue-1/annurev-phyto-080516-035303/20180818/images/medium/py560021.f1.gif
  tags:
    - Highlight
    - Review
- id: doi:10.1186/1471-2148-9-13
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2F1471-2148-9-13/MediaObjects/12862_2008_Article_927_Fig1_HTML.jpg?as=webp
  tags:
    - Mycorrhizal fungi
- id: doi:10.1186/s12864-020-06871-w
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12864-020-06871-w/MediaObjects/12864_2020_6871_Fig2_HTML.png?as=webp
  tags:
    - Zymoseptoria
- id: doi:10.1186/s12864-021-07691-2
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12864-021-07691-2/MediaObjects/12864_2021_7691_Fig1_HTML.png?as=webp
  tags:
    - Zymoseptoria
- id: doi:10.1186/s12866-015-0532-3
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12866-015-0532-3/MediaObjects/12866_2015_532_Fig4_HTML.gif?as=webp
  tags:
    - Human pathogens
- id: doi:10.1186/s12915-016-0309-7
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12915-016-0309-7/MediaObjects/12915_2016_309_Fig1_HTML.gif?as=webp
  tags:
    - Wheat blast
- id: doi:10.1186/s12915-017-0457-4
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12915-017-0457-4/MediaObjects/12915_2017_457_Fig2_HTML.gif?as=webp
  tags:
    - Zymoseptoria
- id: doi:10.1186/s12915-018-0543-2
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12915-018-0543-2/MediaObjects/12915_2018_543_Fig1_HTML.png?as=webp
  tags:
    - Zymoseptoria
- id: doi:10.1186/s12915-020-0744-3
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12915-020-0744-3/MediaObjects/12915_2020_744_Fig2_HTML.png?as=webp
  tags:
    - Zymoseptoria
- id: doi:10.1186/s12915-022-01422-z
  type: paper
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1186%2Fs12915-022-01422-z/MediaObjects/12915_2022_1422_Fig5_HTML.png?as=webp
  tags:
    - Zymoseptoria
- id: doi:10.1371/journal.pbio.3002052
  type: paper
  image: https://journals.plos.org/plosbiology/article/figure/image?download&size=large&id=10.1371/journal.pbio.3002052.g001
  tags:
    - Wheat blast   
- id: doi:10.1371/journal.pgen.1003567
  type: paper
- id: doi:10.1371/journal.pgen.1004438
  type: paper
- id: doi:10.1371/journal.ppat.1008652
  type: paper
  image: https://journals.plos.org/plospathogens/article/figure/image?size=large&id=10.1371/journal.ppat.1008652.g001
  tags:
    - Zymoseptoria
- id: doi:10.1371/journal.ppat.1010149
  type: paper
- id: doi:10.1371/journal.ppat.1011130
  type: paper
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/9970103/bin/ppat.1011130.g007.jpg
  tags:
    - Highlight
    - TEs
    - Zymoseptoria
- id: doi:10.1534/g3.114.015289
- id: doi:10.1534/g3.120.401375
- id: doi:10.1534/genetics.115.180968
- id: doi:10.1590/1678-4685-GMB-2021-0051
- id: doi:10.3389/fmicb.2018.00660
- id: doi:10.3389/fpls.2017.00119
- id: doi:10.3767/persoonia.2021.46.04
- id: doi:10.7554/eLife.56279
  type: paper
  image: https://iiif.elifesciences.org/lax/56279%2Felife-56279-fig1-v1.tif/full/,1500/0/default.jpg
  tags:
    - Highlight
- id: doi:10.7554/eLife.69249
  type: paper
  image: https://iiif.elifesciences.org/lax/69249%2Felife-69249-fig6-v1.tif/full/,1500/0/default.jpg
  tags:
    - Highlight
    - TEs
    - Zymoseptoria

