- id: doi:10.1101/2023.03.29.534750
  type: preprint
  image: https://www.biorxiv.org/content/biorxiv/early/2023/03/29/2023.03.29.534750/F3.large.jpg?width=800&height=600&carousel=1
  tags: 
    - bioRxiv
    - TEs
    - Zymoseptoria
- id: doi:10.1101/2023.03.29.534637
  type: preprint
  image: https://www.biorxiv.org/content/biorxiv/early/2023/03/29/2023.03.29.534637/F5.large.jpg?width=800&height=600&carousel=1
  tags: 
    - bioRxiv
    - TEs
    - Zymoseptoria